project_id = "mzcwbqrvoknysnzjgbkc"

[functions.send-contact-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.ai-conversation]
verify_jwt = true

[functions.road-signs-helper]
verify_jwt = true

[functions.driver-chat]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.generate-suggestions]
verify_jwt = true

[functions.analyze-recording]
verify_jwt = true
